# Generated by Django 5.1.4 on 2024-12-26 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseApp', '0002_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day_name', models.CharField(max_length=10)),
                ('Off', models.CharField(max_length=15)),
                ('Image', models.ImageField(upload_to='')),
            ],
        ),
    ]
