# Generated by Django 5.1.4 on 2024-12-26 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseApp', '0003_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='Rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
    ]
