# Generated by Django 5.1.4 on 2024-12-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseApp', '0006_feedback_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='Rating',
            field=models.IntegerField(blank=True),
        ),
    ]
