# Generated by Django 5.1.4 on 2024-12-29 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BaseApp', '0009_cart_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='product',
            new_name='item',
        ),
    ]
