# Generated by Django 5.1.4 on 2024-12-29 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BaseApp', '0010_rename_product_cartitem_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemlist',
            old_name='Categroy_name',
            new_name='Category_name',
        ),
    ]
